source 'https://rubygems.org'
gem 'sinatra'
gem 'rake'
gem 'rails'
gem 'slim'
gem 'coffee-script'
gem 'sass'
gem 'activesupport', :require => 'active_support/all'

gem 'pg'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-validations-i18n'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'